name: griya_rt_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.22.0
  cloud_firestore: 4.13.1
  firebase_auth: 4.14.0
  firebase_storage: 11.5.1
  nb_utils: 6.0.6
  intl: 0.18.1
  image_picker: ^1.0.4
  convex_bottom_bar: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
  assets: 
    - assets/icons/logo_home.png
    - assets/icons/logo_login.png
    - assets/bgLR.png
    - assets/bgLR.jpg
  uses-material-design: true

